CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE >=0),
    QUANTITY BIGINT NOT NULL CHECK (QUANTITY >=0)
);

CREATE SEQUENCE PRODUCT_SEQUENCE_ID START WITH (SELECT MAX(ID) + 1 FROM PRODUCT);